#!/usr/bin/env python3
"""
Rebuild data/plain-products-tiered.js from Tiered_Pricing_Quote_With_SEO.xlsx,
filtered to non-branded product codes in New Cost list.xlsx.

Usage:
  python scripts/sync-plain-catalog-from-cost-list.py
  python scripts/sync-plain-catalog-from-cost-list.py [cost_list.xlsx] [tiered_pricing.xlsx]
"""

import re
import sys
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("Install openpyxl: pip install openpyxl")
    sys.exit(1)


def slugify(text):
    if text is None:
        return "product"
    s = str(text).strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[-\s]+", "-", s)
    return s[:80] or "product"


def load_allowed_codes(cost_path: Path) -> set[str]:
    wb = openpyxl.load_workbook(cost_path, read_only=True, data_only=True)
    ws = wb["Non-Branded Cost List"]
    codes = set()
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[0]:
            codes.add(str(row[0]).strip())
    wb.close()
    return codes


def load_tiered_products(tiered_path: Path) -> list[dict]:
    wb = openpyxl.load_workbook(tiered_path, read_only=True, data_only=True)
    ws = wb["Tiered Pricing"]
    rows = list(ws.iter_rows(values_only=True))
    wb.close()

    products = []
    seen_ids = set()

    for r in rows[1:]:
        if not r or not r[1]:
            continue
        code = r[0]
        category = (r[1] or "").strip()
        name = (r[2] or "").strip()
        qty_per_case = r[3]
        seo_desc = (r[4] or "").strip() if len(r) > 4 else ""
        p3 = r[8] if len(r) > 8 else None
        p6 = r[9] if len(r) > 9 else None
        p9 = r[10] if len(r) > 10 else None
        p12 = r[11] if len(r) > 11 else None

        if not name or code is None or not str(code).strip():
            continue

        code_str = str(code).strip()
        base_slug = slugify(code_str)
        uid = base_slug
        counter = 0
        while uid in seen_ids:
            counter += 1
            uid = f"{base_slug}-{counter}"
        seen_ids.add(uid)

        case_tiers = []
        for label, val in [
            ("1-3 cases", p3),
            ("4-6 cases", p6),
            ("7-9 cases", p9),
            ("10+ cases", p12),
        ]:
            if val is None:
                continue
            try:
                case_tiers.append({"casesLabel": label, "pricePerCase": float(val)})
            except (TypeError, ValueError):
                pass

        description = (seo_desc or name) + (
            " | Bulk wholesale Ireland" if "Ireland" not in (seo_desc or "") else ""
        )

        products.append(
            {
                "id": uid,
                "code": code_str,
                "name": name,
                "category": category or "Other",
                "qtyPerCase": str(qty_per_case).strip() if qty_per_case is not None else "",
                "description": description[:500] if description else name,
                "caseTiers": case_tiers,
                "imageSrc": "/images/ifa/heroh/logos/logo.png",
                "images": ["/images/ifa/heroh/logos/logo.png"],
            }
        )

    return products


def esc_js(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def write_tiered_js(products: list[dict], out_path: Path) -> None:
    categories = sorted({p["category"] for p in products if p["category"]})
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/sync-plain-catalog-from-cost-list.py\n")
        f.write("// Source: New Cost list.xlsx (non-branded) + Tiered_Pricing_Quote_With_SEO.xlsx\n")
        f.write("// Do not edit by hand. Re-run the script after cost list or pricing updates.\n\n")
        f.write("export const TIERED_PLAIN_PRODUCTS = [\n")
        for p in products:
            ct = ", ".join(
                f'{{ casesLabel: "{t["casesLabel"]}", pricePerCase: {t["pricePerCase"]} }}'
                for t in p["caseTiers"]
            )
            f.write("  {\n")
            f.write(f'    id: "{esc_js(p["id"])}",\n')
            f.write(f'    code: "{esc_js(p["code"])}",\n')
            f.write(f'    name: "{esc_js(p["name"])}",\n')
            f.write(f'    category: "{esc_js(p["category"])}",\n')
            f.write(f'    qtyPerCase: "{esc_js(p["qtyPerCase"])}",\n')
            f.write(f'    description: "{esc_js(p["description"][:400])}",\n')
            f.write(f"    caseTiers: [{ct}],\n")
            f.write(f'    imageSrc: "{p["imageSrc"]}",\n')
            f.write(f'    images: {repr(p["images"])},\n')
            f.write("  },\n")
        f.write("];\n\n")
        f.write("export const TIERED_CATEGORIES = ")
        f.write(repr(categories))
        f.write(";\n")


def main():
    repo_root = Path(__file__).resolve().parent.parent
    cost_path = Path(sys.argv[1]) if len(sys.argv) > 1 else repo_root / "New Cost list.xlsx"
    tiered_path = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else repo_root / "Tiered_Pricing_Quote_With_SEO.xlsx"
    )
    if not tiered_path.exists():
        tiered_path = Path.home() / "Downloads" / "Tiered_Pricing_Quote_With_SEO.xlsx"

    if not cost_path.exists():
        print(f"Cost list not found: {cost_path}")
        sys.exit(1)
    if not tiered_path.exists():
        print(f"Tiered pricing file not found: {tiered_path}")
        sys.exit(1)

    allowed = load_allowed_codes(cost_path)
    all_products = load_tiered_products(tiered_path)
    by_code = {p["code"]: p for p in all_products}

    missing_in_tiered = sorted(allowed - set(by_code))
    if missing_in_tiered:
        print(f"WARNING: {len(missing_in_tiered)} cost-list codes missing from tiered pricing:")
        for code in missing_in_tiered[:20]:
            print(f"  - {code}")
        if len(missing_in_tiered) > 20:
            print(f"  ... and {len(missing_in_tiered) - 20} more")

    products = [by_code[c] for c in sorted(allowed, key=lambda x: (by_code[x]["category"].lower() if x in by_code else "", x)) if c in by_code]
    products.sort(key=lambda p: (p["category"].lower(), p["code"]))

    out_path = repo_root / "data" / "plain-products-tiered.js"
    write_tiered_js(products, out_path)

    print(f"Allowed codes (non-branded): {len(allowed)}")
    print(f"Wrote {len(products)} products to {out_path}")
    print(f"Categories: {len({p['category'] for p in products})}")

    if len(products) != len(allowed):
        print(f"NOTE: expected {len(allowed)} products, wrote {len(products)}")


if __name__ == "__main__":
    main()
